# Welcome to Jekyll!

title:            Miskat Alam Internasional
email:            "miskatinternasional@gmil.com"
description: >- # this means to ignore newlines until "baseurl:"
  An event organizer company in Jakarta
baseurl:          "" # the subpath of your site, e.g. /blog
url:              "http://miskateo.id" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: miskateo.id
github_username:  miskatevent

repository:       "miskatevent/miskatevent.github.io"
lang:             "en"

title-img:        "/assets/img/logo-mai-baru.svg"

# Pagination Settings
# pagination:
#   enabled: true
#   per_page: 10
#   offset: 0
#   permalink: '/:num/'
#   title: ':title - page :num of :max'
#   limit: 0
#   sort_field: 'date'
#   sort_reverse: true

paginate: 10
paginate_path: "/projects/project:num/"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
